name: Mcserversearcher
description: A simple command-line application.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.3.0 <3.0.0'

dependencies:
  utf: ^0.9.0+5

dev_dependencies:
  pedantic: ^1.11.0
